<!DOCTYPE html>
<html lang="en">
    
    


    <head>
    <link href="https://gmpg.org/xfn/11" rel="profile">
    <meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<!-- Enable responsiveness on mobile devices -->
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
<meta name="generator" content="Hugo 0.79.1" />

    
    
    

<title>From RxJava to Kotlin Flow: Error Handling • Vasya Drobushkov</title>


<meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="From RxJava to Kotlin Flow: Error Handling"/>
<meta name="twitter:description" content="Comparing Error Handling in RxJava and Kotlin Flow"/>

<meta property="og:title" content="From RxJava to Kotlin Flow: Error Handling" />
<meta property="og:description" content="Comparing Error Handling in RxJava and Kotlin Flow" />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://krossovochkin.com/posts/2020_02_24_from_rxjava_to_kotlin_flow_error_handling/" />
<meta property="article:published_time" content="2020-02-24T00:00:00+00:00" />
<meta property="article:modified_time" content="2020-02-24T00:00:00+00:00" /><meta property="og:site_name" content="Krossovochkin" />


    


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/androidstudio.min.css">








<link rel="stylesheet" href="/scss/hyde-hyde.adf8a0af011d3afb07ed907ad3295e1c99f49503bc91d395e38dc3f8dfdf4900.css" integrity="sha256-rfigrwEdOvsH7ZB60yleHJn0lQO8kdOV443D&#43;N/fSQA=">


<link rel="stylesheet" href="/scss/print.2744dcbf8a0b2e74f8a50e4b34e5f441be7cf93cc7de27029121c6a09f9e77bc.css" integrity="sha256-J0Tcv4oLLnT4pQ5LNOX0Qb58&#43;TzH3icCkSHGoJ&#43;ed7w=" media="print">



    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon-144-precomposed.png">
    <link rel="shortcut icon" href="/favicon.png">
    
    

</head>


    <body class="theme-base-0a ">
    
<div class="sidebar">
  <div class="container ">
    <div class="sidebar-about">
      <span class="site__title">
        <a href="https://krossovochkin.com/">
        
          Vasya Drobushkov
        
        </a>
      </span>
      
        
        
        
        <div class="author-image">
          <img src="https://krossovochkin.com/../img/avatar.png" alt="Author Image" class="img--circle img--headshot element--center">
        </div>
        
      
      
      <p class="site__description">
        
      </p>
    </div>
    <div class="collapsible-menu">
      <input type="checkbox" id="menuToggle">
      <label for="menuToggle">Vasya Drobushkov</label>
      <div class="menu-content">
        <div>
	<ul class="sidebar-nav">
		 
		 
			 
				<li>
					<a href="/posts/">
						<span>Posts</span>
					</a>
				</li>
			 
		 
			 
				<li>
					<a href="/about/">
						<span>About</span>
					</a>
				</li>
			 
		
	</ul>
</div>

        <section class="social">
	
	<a href="https://twitter.com/krossovochkin" rel="me"><i class="fab fa-twitter fa-lg" aria-hidden="true"></i></a>
	
	
	
	<a href="https://facebook.com/vasya.drobushkov" rel="me"><i class="fab fa-facebook-f"></i></a>
	
	
	<a href="https://github.com/krossovochkin" rel="me"><i class="fab fa-github fa-lg" aria-hidden="true"></i></a>
	
	
	
	
	
	
	
	<a href="https://linkedin.com/in/vasyadrobushkov" rel="me"><i class="fab fa-linkedin fa-lg" aria-hidden="true"></i></a>
	
	
	
	<a href="https://stackoverflow.com/users/1533933/krossovochkin" rel="me"><i class="fab fa-stack-overflow fa-lg" aria-hidden="true"></i></a>
	
	
	
	
	
	
	
	
	
	
	
</section>

      </div>
    </div>
    
<div class="copyright">
  &copy; 2019 - 2021 Vasya Drobushkov
  
    <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>
  
</div>



  </div>
</div>

        <div class="content container">
            
    
<article>
  <header>
    <h1>From RxJava to Kotlin Flow: Error Handling</h1>
    
    
<div class="post__meta">
    
    
      <i class="fas fa-calendar-alt"></i> Feb 24, 2020
    
    
    
    
    
      
      
          <br/>
           <i class="fas fa-tags"></i>
          
          <a class="badge badge-tag" href="/tags/rxjava">rxjava</a>
           
      
          <a class="badge badge-tag" href="/tags/kotlin">kotlin</a>
           
      
          <a class="badge badge-tag" href="/tags/kotlin-flow">kotlin flow</a>
          
      
    
    
    <br/>
    <i class="fas fa-clock"></i> 12 min read
</div>


  </header>
  
  
  <div class="post">
    <p><img src="https://images.unsplash.com/photo-1580357991342-89ec1672c98a?ixlib=rb-1.2.1&amp;auto=format&amp;fit=crop&amp;w=1357&amp;q=80" alt="Source"><em><a href="https://unsplash.com/photos/aYNyC6fIH84">Source</a></em></p>
<blockquote>
<p>This post is part of series of comparing RxJava to Kotlin Flow. Previous articles were about <a href="https://proandroiddev.com/from-rxjava-2-to-kotlin-flow-threading-8618867e1955">Threading </a>and <a href="https://proandroiddev.com/from-rxjava-to-kotlin-flow-backpressure-d1fb91e6dea8">Backpressure</a>.</p>
</blockquote>
<p><a href="https://proandroiddev.com/from-rxjava-to-kotlin-flow-error-handling-da1f6a4f2708"><img src="https://img.shields.io/badge/original-proandroiddev-green#badge" alt=""></a></p>
<h2 id="introduction">Introduction</h2>
<p>Error handling is fundamental in reactive programming. Reactive streams might fail with exception and propagate it as an event downstream notifying consumers on the error that happened.
As in previous articles, we’ll try to compare RxJava and Kotlin Flow error handling mechanisms. This might help us to migrate existing code from RxJava to Kotlin Flow and also understand how to properly use Kotlin Flow.</p>
<h2 id="rxjava-error-handling">RxJava Error Handling</h2>
<p>In RxJava general concepts for error handling are pretty simple and straightforward:</p>
<ul>
<li>
<p>“Error” is an event which might happen in a stream</p>
</li>
<li>
<p>That “Error event” is propagated downstream as a terminal event. That means that after error happened stream is basically finished and no more events can come through it.</p>
</li>
<li>
<p>Consumers are required to handle errors in the onError callback of Observer</p>
</li>
<li>
<p>If Consumer didn’t handle error in Observer callback, then that error is sent to a global error handler (which in case of Android crashes the app by default).
<strong>NOTE</strong>: some errors which happen inside stream can go directly to global error handler e.g. in cases when the stream is already disposed.</p>
</li>
<li>
<p>Not a single error can escape chain. All the exceptions will go to the onError callback of Observer (or global error handler).</p>
</li>
</ul>
<p>A basic example of error handling is:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-kotlin" data-lang="kotlin">observeChanges()
    .subscribe(
        { value <span style="color:#f92672">-&gt;</span> println(<span style="color:#e6db74">&#34;value: </span><span style="color:#e6db74">$value</span><span style="color:#e6db74">&#34;</span>) },
        { error <span style="color:#f92672">-&gt;</span> println(<span style="color:#e6db74">&#34;error: </span><span style="color:#e6db74">$error</span><span style="color:#e6db74">&#34;</span>) }
    )
</code></pre></div><h2 id="kotlin-flow-error-handling">Kotlin Flow Error Handling</h2>
<p>As Kotlin Flow is essentially based on coroutines, the following applies:</p>
<ul>
<li>
<p>“Error” is a general Exception which can be thrown like any other exception</p>
</li>
<li>
<p>That “error” is propagated via general coroutines error handling mechanism (propagating to parent jobs and canceling all the jobs in the coroutine scope)</p>
</li>
<li>
<p>Consumers need to wrap Flow with try-catch if they want to handle exceptions</p>
</li>
<li>
<p>If the consumer didn’t handle errors with try-catch then that exception will be thrown as usual and be handled by the parent coroutine scope (it might immediately crash your app or be handled by exception handler e.g. in launch)</p>
</li>
<li>
<p>As we have to wrap chain in try-catch it looks like exception escaped the chain. It might be partially true, though as we’ll see later this is not the only mechanism to work with exceptions.</p>
</li>
</ul>
<h2 id="comparison">Comparison</h2>
<h3 id="setup">Setup</h3>
<p>First of all, for our comparison, we’ll create helper functions of Flow and Observable, which emit a value and then throw an exception.</p>
<p>For Observable:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-kotlin" data-lang="kotlin"><span style="color:#66d9ef">private</span> <span style="color:#66d9ef">fun</span> <span style="color:#a6e22e">observable</span>(
    value: Int = <span style="color:#ae81ff">1</span>
): Observable&lt;Int&gt; {
    <span style="color:#66d9ef">return</span> Observable.create { emitter <span style="color:#f92672">-&gt;</span>
        emitter.onNext(value)
        emitter.onError(RuntimeException())
    }
}
</code></pre></div><p>And for Kotlin Flow (due to clash of names have to name it with “my” prefix):</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-kotlin" data-lang="kotlin"><span style="color:#66d9ef">private</span> <span style="color:#66d9ef">fun</span> <span style="color:#a6e22e">myFlow</span>(
    value: Int = <span style="color:#ae81ff">1</span>
): Flow&lt;Int&gt; {
    <span style="color:#66d9ef">return</span> flow {
        emit(value)
        <span style="color:#66d9ef">throw</span> RuntimeException()
    }
}
</code></pre></div><p>Next, we’ll set up short tests, which will be parametrized by operators. In that test we’ll take our test streams, subscribe to them on the io thread pool, then optionally will apply some operator and then print values and errors which will happen in the chain.</p>
<p>For Observable:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-kotlin" data-lang="kotlin"><span style="color:#66d9ef">private</span> <span style="color:#66d9ef">fun</span> <span style="color:#a6e22e">testObservable</span>(
    <span style="color:#66d9ef">operator</span>: Observable&lt;Int&gt;.() <span style="color:#f92672">-&gt;</span> Observable&lt;Int&gt;
) {
    <span style="color:#66d9ef">val</span> latch = CountDownLatch(<span style="color:#ae81ff">1</span>)
    <span style="color:#66d9ef">val</span> result = StringBuffer()

observable()
        .subscribeOn(Schedulers.io())
        .<span style="color:#66d9ef">operator</span>()
        .doOnTerminate { latch.countDown() }
        .subscribe(
            { result.append(<span style="color:#e6db74">&#34;next </span><span style="color:#e6db74">$it</span><span style="color:#e6db74">, &#34;</span>) },
            { result.append(<span style="color:#e6db74">&#34;error </span><span style="color:#e6db74">$it</span><span style="color:#e6db74">&#34;</span>) }
        )

latch.await()
    println(result)
}
</code></pre></div><p>For Kotlin Flow (note, that here we wrapped all the flow into the try-catch):</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-kotlin" data-lang="kotlin"><span style="color:#66d9ef">private</span> <span style="color:#66d9ef">fun</span> <span style="color:#a6e22e">testFlow</span>(
    <span style="color:#66d9ef">operator</span>: Flow&lt;Int&gt;.() <span style="color:#f92672">-&gt;</span> Flow&lt;Int&gt;
) {
    <span style="color:#66d9ef">val</span> latch = CountDownLatch(<span style="color:#ae81ff">1</span>)
    <span style="color:#66d9ef">val</span> result = StringBuffer()

    CoroutineScope(Job() + Dispatchers.IO).launch {
        <span style="color:#66d9ef">try</span> {
            myFlow()
                .<span style="color:#66d9ef">operator</span>()
                .onCompletion { latch.countDown() }
                .collect {
                    result.append(<span style="color:#e6db74">&#34;next </span><span style="color:#e6db74">$it</span><span style="color:#e6db74">, &#34;</span>)
                }
        } <span style="color:#66d9ef">catch</span> (e: Exception) {
            result.append(<span style="color:#e6db74">&#34;error </span><span style="color:#e6db74">$e</span><span style="color:#e6db74">&#34;</span>)
        }
    }

    latch.await()
    println(result)
}
</code></pre></div><h3 id="basic-error-handling">Basic Error Handling</h3>
<p>First, our test will be to see what is the default behavior without additional changes. In this case, we’ll provide an identity operator:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-kotlin" data-lang="kotlin">testObservable { <span style="color:#66d9ef">this</span> }
testFlow { <span style="color:#66d9ef">this</span> }
</code></pre></div><p>In both cases in logs it will be printed:</p>
<pre><code>next 1, error java.lang.RuntimeException
</code></pre><p>So, as we already discussed, our test streams emit one value and then terminate with an exception.</p>
<h3 id="catching-errors-with-an-emitting-default-value">Catching Errors with an emitting default value</h3>
<p>What if we don’t want our stream to be terminated (as error event terminates the stream)? One of the options is to emit some default value if we encounter an exception.</p>
<p>In RxJava for that, there is a special operator called onErrorReturn:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-kotlin" data-lang="kotlin">testObservable { onErrorReturn { <span style="color:#ae81ff">5</span> } }
</code></pre></div><p>If we run this example we’ll see that in logs it will be printed:</p>
<pre><code>next 1, next 5,
</code></pre><p>So the first item in the stream (1) was emitted as before, but then instead of an error, we have a default value (5) emitted as well.</p>
<p>In Kotlin Flow for the same use case, there is an operator catch, and the usage is the following:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-kotlin" data-lang="kotlin">testFlow { <span style="color:#66d9ef">catch</span> { emit(<span style="color:#ae81ff">5</span>) } }
</code></pre></div><p>Operator catch catches all the exceptions from the upstream and can do some work, such as emitting default value. And result in logs will be the same.</p>
<h3 id="catching-errors-by-switching-to-another-stream">Catching Errors by switching to another stream</h3>
<p>Another option with not failing our stream on error is to switch to another stream. In RxJava for that, there is a special operator onErrorResumeNext:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-kotlin" data-lang="kotlin">testObservable { onErrorResumeNext(Observable.just(<span style="color:#ae81ff">1</span>, <span style="color:#ae81ff">2</span>, <span style="color:#ae81ff">3</span>)) }
</code></pre></div><p>After running the code the result will be:</p>
<pre><code>next 1, next 1, next 2, next 3,
</code></pre><p>First, we have the value of 1 emitted (this is from the initial stream), then after error happened we switch to the new stream and all its values are emitted (and we won’t have an exception thrown).</p>
<blockquote>
<p><strong>NOTE</strong>: Essentially it is possible to achieve onErrorReturn with onErrorResumeNext by using onErrorResumeNext(Observable.just(5)), though usage of onErrorResumeNext has bigger overhead, so use it only when new stream is really needed.</p>
</blockquote>
<p>In Kotlin Flow for such a case we use that same operator catch:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-kotlin" data-lang="kotlin">testFlow { <span style="color:#66d9ef">catch</span> { emitAll(flowOf(<span style="color:#ae81ff">1</span>, <span style="color:#ae81ff">2</span>, <span style="color:#ae81ff">3</span>)) } }
</code></pre></div><p>Instead of emitting a single value on error, we emitAll values from the stream with the same expected result.</p>
<h3 id="intercepting-errors">Intercepting Errors</h3>
<p>The next thing which we’ll do is intercepting errors. When we intercept errors we can do some side effects without actually handling that error, for example, logging.</p>
<p>In RxJava for this case, we can use the doOnError operator:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-kotlin" data-lang="kotlin">testObservable { doOnError { print(<span style="color:#e6db74">&#34;INTERCEPTED </span><span style="color:#e6db74">$it</span><span style="color:#e6db74">, &#34;</span>) } }
</code></pre></div><p>The result will be:</p>
<pre><code>INTERCEPTED java.lang.RuntimeException, next 1, error java.lang.RuntimeException
</code></pre><p>So, first, we intercepted our exception, printed some logs, and then as in the case with basic error handling, we got the first item emitted with error followed.</p>
<p>In Kotlin Flow though there is no special operator for that case, but we can write our own:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-kotlin" data-lang="kotlin"><span style="color:#66d9ef">fun</span> &lt;<span style="color:#a6e22e">T</span>&gt; <span style="color:#a6e22e">Flow</span>&lt;T&gt;.doOnError(onError: (Throwable) <span style="color:#f92672">-&gt;</span> Unit): Flow&lt;T&gt; {
    <span style="color:#66d9ef">return</span> flow {
        <span style="color:#66d9ef">try</span> {
            collect { value <span style="color:#f92672">-&gt;</span>
                emit(value)
            }
        } <span style="color:#66d9ef">catch</span> (e: Exception) {
            onError(e)
            <span style="color:#66d9ef">throw</span> e
        }
    }
}
</code></pre></div><p>Here we just create new Flow, inside it, we start collecting all the values. We wrap everything in try-catch and if an error happens — we’ll execute the callback and re-throw exception.</p>
<p>The usage will be the following:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-kotlin" data-lang="kotlin">testFlow { doOnError { print(<span style="color:#e6db74">&#34;INTERCEPTED </span><span style="color:#e6db74">$it</span><span style="color:#e6db74">, &#34;</span>) } }
</code></pre></div><p>And as before, results in logs will be the same.</p>
<p>That’s all with the handling errors in the chain, but there is another topic of handling errors in inner streams.</p>
<h3 id="inner-streams-errors-handling">Inner streams errors handling</h3>
<p>As we know we can have inner streams by using flatMap in RxJava or flatMapMerge in Flow (or other xMap operators in RxJava or flatMapX operators in Kotlin Flow).
We can apply directly what we’ve learned to our inner streams, though sometimes there is a need to control error handling from the parent stream perspective.</p>
<p>We’ll modify our test samples a bit to better show that.</p>
<p>For Observable our new example will be:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-kotlin" data-lang="kotlin"><span style="color:#66d9ef">private</span> <span style="color:#66d9ef">fun</span> <span style="color:#a6e22e">testInnerObservable</span>(
    <span style="color:#66d9ef">operator</span>: Observable&lt;Int&gt;.() <span style="color:#f92672">-&gt;</span> Observable&lt;Int&gt;
) {
    <span style="color:#66d9ef">val</span> latch = CountDownLatch(<span style="color:#ae81ff">1</span>)
    <span style="color:#66d9ef">val</span> result = StringBuffer()

    Observable.just(<span style="color:#ae81ff">10</span>, <span style="color:#ae81ff">11</span>, <span style="color:#ae81ff">12</span>)
        .subscribeOn(Schedulers.io())
        .<span style="color:#66d9ef">operator</span>()
        .doOnTerminate { latch.countDown() }
        .subscribe(
            { result.append(<span style="color:#e6db74">&#34;next </span><span style="color:#e6db74">$it</span><span style="color:#e6db74">, &#34;</span>) },
            { result.append(<span style="color:#e6db74">&#34;error </span><span style="color:#e6db74">$it</span><span style="color:#e6db74">&#34;</span>) }
        )

    latch.await()
    println(result)
}
</code></pre></div><p>The difference is that now our parent observable won’t throw an exception, instead it will emit three items and complete. Inside operator we’ll be able to add our inner streams.</p>
<p>For Kotlin Flow we’ll have the following sample:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-kotlin" data-lang="kotlin"><span style="color:#66d9ef">private</span> <span style="color:#66d9ef">fun</span> <span style="color:#a6e22e">testInnerFlow</span>(
    <span style="color:#66d9ef">operator</span>: Flow&lt;Int&gt;.() <span style="color:#f92672">-&gt;</span> Flow&lt;Int&gt;
) {
    <span style="color:#66d9ef">val</span> latch = CountDownLatch(<span style="color:#ae81ff">1</span>)
    <span style="color:#66d9ef">val</span> result = StringBuffer()

    CoroutineScope(Job() + Dispatchers.IO).launch {
        <span style="color:#66d9ef">try</span> {
            flowOf(<span style="color:#ae81ff">10</span>, <span style="color:#ae81ff">11</span>, <span style="color:#ae81ff">12</span>)
                .<span style="color:#66d9ef">operator</span>()
                .onCompletion { latch.countDown() }
                .collect {
                    result.append(<span style="color:#e6db74">&#34;next </span><span style="color:#e6db74">$it</span><span style="color:#e6db74">, &#34;</span>)
                }
        } <span style="color:#66d9ef">catch</span> (e: Exception) {
            result.append(<span style="color:#e6db74">&#34;error </span><span style="color:#e6db74">$e</span><span style="color:#e6db74">&#34;</span>)
        }
    }

    latch.await()
    println(result)
}
</code></pre></div><p>There are many different operators in RxJava, but we’ll take a look only at one: concatMapDelayError.
In order to understand how it works, let’s first look at the concatMap and flatMapConcat operators. Both these operators start subscribing to the inner streams one by one. And subscription to the next inner stream happens only when previous was completed.</p>
<p>For RxJava and Kotlin Flow it will look like:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-kotlin" data-lang="kotlin">testInnerObservable { concatMap { observable(<span style="color:#66d9ef">it</span>) } }
testInnerFlow { flatMapConcat { myFlow(<span style="color:#66d9ef">it</span>) } }
</code></pre></div><p>What happens here:</p>
<ul>
<li>
<p>Our parent stream has three values</p>
</li>
<li>
<p>For each value emitted we switch to the new inner stream (which emits value and then fails)</p>
</li>
<li>
<p>Subscription to the next inner stream happens only after the previous inner stream has completed</p>
</li>
</ul>
<p>Result of executing for RxJava and Kotlin Flow will be the same:</p>
<pre><code>next 10, error java.lang.RuntimeException
</code></pre><p>We have first item emitted followed by an error and no more values are emitted. This happens because the first item (10) triggered a subscription of the inner stream, which emitted that value (10) and then failed with an exception. Because of that, the whole stream failed and the next item from parent (11) hasn’t been switched to the new inner stream.</p>
<p>What if we want to have all the values emitted and emit error only in the end (if it happened)? For such a case there is concatMapDelayError in RxJava. It will delay all the errors until the stream completes and throw CompositeException with all the exceptions which happened in the stream.</p>
<p>If we run the following code:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-kotlin" data-lang="kotlin">testInnerObservable { concatMapDelayError { observable(<span style="color:#66d9ef">it</span>) } }
</code></pre></div><p>We see the result:</p>
<pre><code>next 10, next 11, next 12, error io.reactivex.exceptions.CompositeException: 3 exceptions occurred.
</code></pre><p>All three items were emitted followed by a single composite exception (which has three exceptions inside — one per each inner stream).</p>
<p>What about Kotlin Flow? It doesn’t have any operator with delaying errors. But we can try to write our own. We’ll start by copy-pasting sources of flatMapConcat operator and add some error handling there:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-kotlin" data-lang="kotlin"><span style="color:#66d9ef">fun</span> &lt;<span style="color:#a6e22e">T</span>, <span style="color:#a6e22e">R</span>&gt; <span style="color:#a6e22e">Flow</span>&lt;T&gt;.flatMapConcatDelayError(
    transform: <span style="color:#66d9ef">suspend</span> (value: T) <span style="color:#f92672">-&gt;</span> Flow&lt;R&gt;
): Flow&lt;R&gt; = map(transform).flattenConcatDelayError()
</code></pre></div><p>We’ll start from defining our operator flatMapConcatDelayError as combination of map and flatten (yep, map + flatten == flatMap).
Then we’ll define our flattenConcatDelayError:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-kotlin" data-lang="kotlin"><span style="color:#66d9ef">fun</span> &lt;<span style="color:#a6e22e">T</span>&gt; <span style="color:#a6e22e">Flow</span>&lt;Flow&lt;T&gt;&gt;.flattenConcatDelayError(): Flow&lt;T&gt; {
    <span style="color:#66d9ef">val</span> list = CopyOnWriteArrayList&lt;Exception&gt;()
    <span style="color:#66d9ef">return</span> flow&lt;T&gt; {
        collect { value <span style="color:#f92672">-&gt;</span>
            <span style="color:#66d9ef">try</span> {
                emitAll(value)
            } <span style="color:#66d9ef">catch</span> (e: Exception) {
                list.add(e)
            }
        }
    }.onCompletion {
        <span style="color:#66d9ef">if</span> (list.isNotEmpty()) {
            <span style="color:#66d9ef">throw</span> CompositeException(list)
        }
    }
}
</code></pre></div><p>What we do here is wrap our emits into try-catch with saving all the exceptions (note that we need to use thread-safe list). And throw a composite exception at the end if there were some exceptions.</p>
<p>Final call for Kotlin Flow will be:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-kotlin" data-lang="kotlin">testInnerFlow { flatMapConcatDelayError { myFlow(<span style="color:#66d9ef">it</span>) } }
</code></pre></div><h3 id="rxjava-like-subscribe-for-kotlin-flow">RxJava-like subscribe for Kotlin Flow</h3>
<p>Do I need to always use either catch at the bottom of each chain or wrap everything into try-catch? I’d say yes, but probably it could be useful to have similar API as in RxJava and have single subscribe with three lambdas.</p>
<p>We can try to implement such:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-kotlin" data-lang="kotlin"><span style="color:#66d9ef">suspend</span> <span style="color:#66d9ef">fun</span> &lt;<span style="color:#a6e22e">T</span>&gt; <span style="color:#a6e22e">Flow</span>&lt;T&gt;.subscribe(
    onNext: (T) <span style="color:#f92672">-&gt;</span> Unit,
    onError: (Throwable) <span style="color:#f92672">-&gt;</span> Unit,
    onComplete: () <span style="color:#f92672">-&gt;</span> Unit
) {
    <span style="color:#66d9ef">this</span>
        .onEach { onNext(<span style="color:#66d9ef">it</span>) }
        .onCompletion { error: Throwable? <span style="color:#f92672">-&gt;</span>
            <span style="color:#66d9ef">if</span> (error <span style="color:#f92672">==</span> <span style="color:#66d9ef">null</span>) {
                onComplete()
            }
        }
        .<span style="color:#66d9ef">catch</span> { onError(<span style="color:#66d9ef">it</span>) }
        .collect()
}
</code></pre></div><p>What we do here is instead of terminal collect method, we’ll use our own subscribe, which takes three lambdas.
In onEach we’ll get all the values emitted. In onCompletion we’ll see that we track our onComplete (note that we need to check that we completed without error). And in catch we catch all the exceptions.</p>
<blockquote>
<p><strong>NOTE</strong>: we could move onError inside onCompletion if we wish and make catch clause empty. Say it is matter of taste.</p>
</blockquote>
<p><strong>But did anyone spot the issue?</strong></p>
<p>Let’s run few tests:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-kotlin" data-lang="kotlin">runBlocking {
    flowOf(<span style="color:#ae81ff">1</span>, <span style="color:#ae81ff">2</span>, <span style="color:#ae81ff">3</span>)
        .subscribe(
            { print(<span style="color:#e6db74">&#34;next </span><span style="color:#e6db74">$it</span><span style="color:#e6db74">, &#34;</span>) },
            { print(<span style="color:#e6db74">&#34;error </span><span style="color:#e6db74">$it</span><span style="color:#e6db74">, &#34;</span>) },
            { print(<span style="color:#e6db74">&#34;complete &#34;</span>) }
        )
}
</code></pre></div><p>It prints:</p>
<pre><code>next 1, next 2, next 3, complete
</code></pre><p>So far so good. We have all three values emitted following by completion event.</p>
<p>Next test will be with error:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-kotlin" data-lang="kotlin">runBlocking {
    flow {
        emit(<span style="color:#ae81ff">1</span>)
        <span style="color:#66d9ef">throw</span> RuntimeException()
    }
        .subscribe(
            { print(<span style="color:#e6db74">&#34;next </span><span style="color:#e6db74">$it</span><span style="color:#e6db74">, &#34;</span>) },
            { print(<span style="color:#e6db74">&#34;error </span><span style="color:#e6db74">$it</span><span style="color:#e6db74">, &#34;</span>) },
            { print(<span style="color:#e6db74">&#34;complete &#34;</span>) }
        )
}
</code></pre></div><p>It prints:</p>
<pre><code>next 1, complete error java.lang.RuntimeException,
</code></pre><p>Also good, we have one value followed by error event. And we don’t have a completion event.</p>
<p>Let’s check the final test — we throw exception in a callback:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-kotlin" data-lang="kotlin">runBlocking {
    flow {
        emit(<span style="color:#ae81ff">1</span>)
    }
        .subscribe(
            { print(<span style="color:#e6db74">&#34;next </span><span style="color:#e6db74">$it</span><span style="color:#e6db74">, &#34;</span>) },
            { print(<span style="color:#e6db74">&#34;error </span><span style="color:#e6db74">$it</span><span style="color:#e6db74">, &#34;</span>) },
            { <span style="color:#66d9ef">throw</span> RuntimeException() }
        )
}
</code></pre></div><p>The result will be:</p>
<pre><code>next 1, error java.lang.RuntimeException,
</code></pre><p>And this is not what we’ve expected. If we have an exception in a callback, then it should be thrown and should not pass to our error handler. Error handler should catch all the errors in the chain and callback is not essentially part of that chain.</p>
<p>Why it happens so? Because catch is the last operator in the chain and it handles everything which is above. Including what is inside onEach and onCompletion operators.</p>
<p>This is the difference which is needed to keep in mind. If anyone would be able to create an identical implementation of subscribe method, feel free to post it in comments.</p>
<h2 id="upd-retry">UPD: retry</h2>
<p>As was pointed by feedback I missed in this article operators for retry logic. Basically both RxJava and Kotlin Flow has built-in support for retry. For example to retry stream twice (if there was error) one need to use “retry(2)” operator.</p>
<h2 id="conclusion">Conclusion</h2>
<p>Following this article, I hope we now have a better understanding of error handling in RxJava and Kotlin Flow. RxJava has a lot of operators, many of them are really useful (and are missing in Kotlin Flow right now).</p>
<p>We can write our own implementations, but they stick to be error-prone and platform-specific. Say that flatMapConcatDelayError operator: it uses platform-specific thread-safe list, which might work incorrectly with coroutines (which can jump over threads) — mean that mixing concepts might lead to weird issues. Also, the whole implementation might not be that refined, contain races or whatever.</p>
<p>It is possible to do everything we can do in RxJava with Kotlin Flow and hopefully, additional operators will be added to Kotlin Flow as well.</p>
<p>If anyone wants to play with the setup one can find in <a href="https://gist.github.com/krossovochkin/1a47f05d3ccbf20fffa872b22362e16d">this gist</a>. Feel free to post comments and share your examples or ideas on the important things in error handling in RxJava and Kotlin Flow.</p>
<p>Happy coding!</p>

  </div>
  

<div class="navigation navigation-single">
    
    <a href="/posts/2020_02_21_vinyls_animation_with_motionlayout/" class="navigation-prev">
      <i aria-hidden="true" class="fa fa-chevron-left"></i>
      <span class="navigation-tittle">Vinyls animation with MotionLayout</span>
    </a>
    
    
    <a href="/posts/2020_02_26_from_rxjava_to_kotlin_flow_stream_types/" class="navigation-next">
      <span class="navigation-tittle">From RxJava to Kotlin Flow: Stream Types</span>
      <i aria-hidden="true" class="fa fa-chevron-right"></i>
    </a>
    
</div>


  

  
    


</article>


        </div>
        
    

  
  
<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
	ga('create', 'UA-148934073-1', 'auto');
	
	ga('send', 'pageview');
}
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>


<script defer src="https://use.fontawesome.com/releases/v5.12.1/js/all.js" integrity="sha384-ZbbbT1gw3joYkKRqh0kWyRp32UAvdqkpbLedQJSlnI8iLQcFVxaGyrOgOJiDQTTR" crossorigin="anonymous"></script>


    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/highlight.min.js"></script>
        
            
                <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/languages/bash.min.js"></script>
            
                <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/languages/java.min.js"></script>
            
                <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/languages/kotlin.min.js"></script>
            
        
    <script type="text/javascript">
        
        hljs.configure({languages: ["bash, java, kotlin"]});
        
        hljs.initHighlightingOnLoad();
    </script>
    



    



    </body>
</html>
